name: "system"
runner: "org.osbuild.fedora${fedora.release}"
build: "name:buildroot"
stages:
  - type: org.osbuild.kernel-cmdline
    options:
      root_fs_uuid: ${filesystem.osbuild.const.partition_map.root.uuid}
      kernel_opts: ${kernel.cmdline}
  - otk.external.osbuild-make-depsolve-dnf4-rpm-stage:
      packageset: ${packages.system.osbuild}
      gpgkeys: ${fedora.gpgkeys}
  - type: org.osbuild.fix-bls
    options:
      prefix: ''
  - type: org.osbuild.locale
    options:
      language: C.UTF-8
  - type: org.osbuild.timezone
    options:
      zone: Etc/UTC
  - type: org.osbuild.sysconfig
    options:
      kernel:
        update_default: true
        default_kernel: kernel
      network:
        networking: true
        no_zero_conf: true
  - type: org.osbuild.systemd.unit
    options:
      unit: grub-boot-success.timer
      dropin: 10-disable-if-greenboot.conf
      config:
        Unit:
          ConditionPathExists: '!/usr/libexec/greenboot/greenboot'
      unit-type: global
  - otk.external.osbuild-make-fstab-stage: ${filesystem.osbuild}
  - type: org.osbuild.grub2
    options:
      root_fs_uuid: ${filesystem.osbuild.const.partition_map.root.uuid}
      boot_fs_uuid: ${filesystem.osbuild.const.partition_map.boot.uuid}
      kernel_opts: ${kernel.cmdline}
      uefi:
        vendor: ${fedora.vendor}
        unified: true
      saved_entry: ffffffffffffffffffffffffffffffff-${kernel.package.version}-${kernel.package.release}.${kernel.package.arch}
      write_cmdline: false
      config:
        default: saved
  - type: org.osbuild.copy
    inputs:
      file-kickstart:
        type: org.osbuild.files
        origin: org.osbuild.source
        references:
          - id: ${files.osbuild.const.files.kickstart.id}
    options:
      paths:
        - from: input://file-kickstart/${files.osbuild.const.files.kickstart.id}
          to: tree:///root/anaconda-ks.cfg
          remove_destination: true
  - type: org.osbuild.chown
    options:
      items:
        /root/anaconda-ks.cfg:
          user: root
          group: root

  # TODO from an include for the repart shenanigans :)
  - type: org.osbuild.mkdir
    options:
      paths:
        - path: /usr/lib/repart.d
          parents: true
  - type: org.osbuild.chown
    options:
      items:
        /usr/lib/repart.d:
          user: root
          group: root

  - type: org.osbuild.copy
    inputs:
      file-repart_esp:
        type: org.osbuild.files
        origin: org.osbuild.source
        references:
          - id: ${files.osbuild.const.files.repart_esp.id}
    options:
      paths:
        - from: input://file-repart_esp/${files.osbuild.const.files.repart_esp.id}
          to: tree:///usr/lib/repart.d/00-esp.conf
          remove_destination: true
  - type: org.osbuild.chown
    options:
      items:
        /usr/lib/repart.d/00-esp.conf:
          user: root
          group: root

  - type: org.osbuild.copy
    inputs:
      file-repart_root:
        type: org.osbuild.files
        origin: org.osbuild.source
        references:
          - id: ${files.osbuild.const.files.repart_root.id}
    options:
      paths:
        - from: input://file-repart_root/${files.osbuild.const.files.repart_root.id}
          to: tree:///usr/lib/repart.d/10-root.conf
          remove_destination: true
  - type: org.osbuild.chown
    options:
      items:
        /usr/lib/repart.d/10-root.conf:
          user: root
          group: root

  - type: org.osbuild.copy
    inputs:
      file-repart_swap:
        type: org.osbuild.files
        origin: org.osbuild.source
        references:
          - id: ${files.osbuild.const.files.repart_swap.id}
    options:
      paths:
        - from: input://file-repart_swap/${files.osbuild.const.files.repart_swap.id}
          to: tree:///usr/lib/repart.d/20-swap.conf
          remove_destination: true
  - type: org.osbuild.chown
    options:
      items:
        /usr/lib/repart.d/20-swap.conf:
          user: root
          group: root

  - type: org.osbuild.copy
    inputs:
      file-repart_srv:
        type: org.osbuild.files
        origin: org.osbuild.source
        references:
          - id: ${files.osbuild.const.files.repart_srv.id}
    options:
      paths:
        - from: input://file-repart_srv/${files.osbuild.const.files.repart_srv.id}
          to: tree:///usr/lib/repart.d/30-srv.conf
          remove_destination: true
  - type: org.osbuild.chown
    options:
      items:
        /usr/lib/repart.d/30-srv.conf:
          user: root
          group: root


  - type: org.osbuild.systemd
    options:
      enabled_services:
        - NetworkManager.service
        - firewalld.service
        - sshd.service
        - initial-setup.service
  - type: org.osbuild.selinux
    options:
      file_contexts: etc/selinux/targeted/contexts/files/file_contexts
