name: CI

on:
  push:
  # pull_request:
  # release:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  artifacts:
    name: Build Artifacts
    uses: ./.github/workflows/artifacts.yaml
