name: CI

on:
  push:
  # pull_request:
  # release:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  manifest:
    uses: ./.github/workflows/manifest.yaml
